# Generated by Django 5.2.8 on 2025-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincome',
            name='sand_rate',
            field=models.CharField(blank=True, null=True),
        ),
    ]
