# Generated by Django 5.2.8 on 2025-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_dailyincome_sand_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyincome',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='dailyincome',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
