# Generated by Django 5.2.8 on 2025-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_notes_dailyincome_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincome',
            name='sands_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
