# Generated by Django 5.2.8 on 2026-01-05 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_dailyincome_sands_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
