# Generated by Django 5.2.8 on 2026-01-05 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_partner_share_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincome',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
