# Generated by Django 5.2.8 on 2026-02-11 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_dailyincome_actual_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincome',
            name='daily_food_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
