# Generated by Django 5.2.8 on 2026-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_dailyincome_daily_food_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincome',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
