# Generated by Django 5.2.8 on 2026-01-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
